name = "transcriptor-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ALLOWED_ORIGINS = "https://transcriptor-d31.pages.dev"

[[kv_namespaces]]
binding = "PIN_SECURITY"
id = "ff7af5d8907f4d58a9b46ca1c724fcbd"

# Secrets (set via wrangler secret put):
# REPLICATE_API_TOKEN
# API_PASSWORD
